name: catalog_getx
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  paint_collection: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
