name: flutter_tutorial
repository: https://github.com/mntm/flutter_tutorial

packages:
  - apps/*
  - apps/beginner/*
  - apps/intermediate/*
  - apps/advanced/*
  - packages/*

command:
  version:
    branch: main
    linkToCommits: true

  bootstrap:
    runPubGetInParallel: false
