name: flutter_tutorial
description: A monorepo holding flutter learning tutorial projects
version: 1.0.0
repository: https://github.com/mntm/flutter_tutorial

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
dev_dependencies:
  melos: ^6.1.0
  # path: ^1.8.0


